name: driven
favicon: null
layout_spectrum: 0.6294316214043647
typography_spectrum: 0.2549684913828969
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.305300633655861
  lightness: 0.4590331243816763
  saturation: 0.4142818220425397
  rhythmicContrast: 0.457646360155195
purpose: []
